volunto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from . import views
from volunto.views import ProjectListView , OrganizationListView, ProjectUpdate, ProjectDelete
from .views import ProfileDetail, ProfileUpdate
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (RedirectView, TemplateView)


app_name = 'volunto'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^projects/$', views.ProjectListView.as_view(), name='projects'),
    url(r'^organizations/$', views.OrganizationListView.as_view(), name='organizations'),
    url(r'^projects/create/$', views.ProjectCreate.as_view(), name='project_create'),
    url(r'^create_application/$', views.ApplicationCreate.as_view(), name='create_application'),
    url(r'^create_application/application_sent/$', views.application_sent, name='application_sent'),
    url(r'^project/(?P<pk>\d+)$', views.ProjectDetailView.as_view(), name='project-detail'),
    url(r'^project/update/(?P<pk>\d+)$', views.ProjectUpdate.as_view(), name='project_update'),
    url(r'^project/delete/(?P<pk>\d+)$', views.ProjectDelete.as_view(), name='project_delete'),
    url(r'^organization/(?P<pk>\d+)$', views.OrganizationDetailView.as_view(), name='organization-detail'),
    url(r'^accounts/update/(?P<pk>[\-\w]+)/$', views.edit_profile, name='account_update'),
    url(r'^profile/$',views.ProfileDetail.as_view(), name="profile"),
    url(r'^profile/edit/$', views.ProfileUpdate.as_view(), name="profile_update")
]

voluntoweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm


urlpatterns = [
	url(r'^volunto/', include('volunto.urls', namespace='dj-auth')),
    url(r'^admin/', admin.site.urls),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/volunto/', permanent=True)),
]


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

volunto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, Permission
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import RegexValidator

# Create your models here.

class Organization(models.Model):
	orgname = models.CharField(max_length=200)
	orgdesc = models.TextField(max_length=200)
	orgid = models.AutoField(primary_key=True)
	orgusername = models.CharField(max_length=200)
	orgpw = models.CharField(max_length=30, default="")
	ORG_STATUS = (
		(1, 'Active'),
		(2, 'Inactive'),
		(3, 'In-review')
		)
	orgstat = models.PositiveIntegerField(choices=ORG_STATUS, default=3)
	def __str__(self):
		return self.orgname
	def get_absolute_url(self):
		#Returns a URL for accessing an Organization object instance
		return reverse('volunto:organization-detail', args=(self.orgid,))

class Project(models.Model):
	projectname = models.CharField("Project Name",max_length=200)
	projdesc = models.CharField("Project Description",max_length=500)
	projectid = models.AutoField(primary_key=True)
	projstatus = models.BooleanField("Project Status", default=False)
	orgname = models.ForeignKey(Organization, on_delete=models.CASCADE, verbose_name="Project Sponsor")
	def __str__(self):
		return self.projectname
	def get_absolute_url(self):
		#Returns a URL for accessing a Project object instance
		return reverse('volunto:project-detail', args=(self.projectid,))

class School(models.Model):
	schoolname = models.CharField(max_length=200)
	schooladdress = models.CharField(max_length=200)
	schoolid = models.AutoField(primary_key=True)
	def __str__(self):
		return self.schoolname

class Volunteer(models.Model):
	volunteerid = models.AutoField(primary_key=True)
	school = models.ForeignKey(School,on_delete=models.CASCADE, default=1)
	birth_date = models.DateField(null=True, blank=True)

class Position(models.Model):
	postitle = models.CharField(max_length=50)
	posdesc = models.TextField(max_length=200)
	POS_LEVELS = (
		(1, 'Basic'),
		(2, 'Immediate'),
		(3, 'Advanced')
		)
	level = models.PositiveIntegerField(choices=POS_LEVELS, default=1)
	posid = models.AutoField(primary_key=True)
	project = models.ForeignKey(Project, on_delete=models.CASCADE, default=1)
	def __str__(self):
		return self.postitle

class Application(models.Model):
	applicationid = models.AutoField(primary_key=True)
	project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name="Project Name")
	applicant_firstname = models.CharField("First Name",max_length=30)
	applicant_lastname = models.CharField("Last Name",max_length=30)

class Profile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	slug = models.SlugField(max_length=30,unique=True, null=True, default=None)
	bio = models.TextField(max_length=500, blank=True)
	location = models.CharField(max_length=30, blank=True)
	phone_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$', message="Phone number must be entered in the format: '+2234567899'. Only 10 digits allowed.")
	phone = models.CharField(validators=[phone_regex], max_length=10,blank=True, null=False, unique=True)
	experience_level_choices = (
		(1, 'No Experience'),
		(2, 'Some Experience'),
		(3, 'Experienced with certification')
		)
	experience_level = models.PositiveIntegerField(choices=experience_level_choices, default=1)
	experience_area_choices =(
		(1, 'Technology'),
		(2, 'Hospitality'),
		(3, 'Education'),
		(4, 'Miscellaneous')
		)
	experience_area = models.PositiveIntegerField(choices=experience_area_choices, default=4)
	education_level_choices = (
		(1, 'Secondary'),
		(2, 'Post Secondary')
		)
	education_level = models.PositiveIntegerField(choices=education_level_choices, default=1)

	#Verbose name for Django Admin interface of Profile
	def __str__(self):
		return self.user.username

	#Use to redirect to Profile Update page
	def get_update_url(self):
		return reverse('dj-auth:profile_update')

	def get_absolute_url(self):
		return reverse('dj-auth:profile')
	#Methods to create and update Profile once a User was created
	def create_profile(sender, **kwargs):
		user=kwargs["instance"]
		if kwargs["created"]:
			user_profile = Profile(user=user)
			user_profile.save()
	post_save.connect(create_profile, sender=User)

volunto/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Project, Organization, Profile, Volunteer, Application, School
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


class UserForm(forms.ModelForm):
	username = forms.CharField(max_length=30,min_length=5)
	password = forms.CharField(widget=forms.PasswordInput)
	email = forms.EmailField(widget=forms.EmailInput, required=True)
	class Meta: 
		model = User
		fields = ['username', 'email', 'password']

	#Clean username data field to avoid conflict with URL slugging	
	def clean_username(self):
		username = self.cleaned_data['username']
		disallowed = ('activate', 'create', 'disable', 'login', 'logout', 'password', 'profile',)
		if username in disallowed:
			raise ValidationError("A user with that username already exists")
		return username

	#Clean email and check to see if user with same email is already registered
	def clean_email(self):
		email = self.cleaned_data.get('email')
		# Check to see if any users already exist with this email as a username.
		try:
			match = User.objects.get(email=email)
		except User.DoesNotExist:
			return email
		raise forms.ValidationError('This email address is already in use.')


class ProjectsForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['projectname', 'projdesc', 'projstatus', 'orgname']

class OrganizationForm(forms.ModelForm):
	class Meta:
		model = Organization
		fields = ['orgname', 'orgdesc']

#Form for User profile and to be extended using the Profile model
class UserCreationForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']

volunto/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm, ProjectsForm
from django.views import generic
from django.views.generic import DetailView, View
from .models import Project, Organization, Application, Profile
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, Permission
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from .utils import (ProfileGetObjectMixin)
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse, reverse_lazy, resolve


def index(request):
	return render(request, 'volunto/index.html')

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return render(request, 'volunto/index.html')
			else:
				return render(request, 'volunto/login.html', {'error_message': 'Account is disabled.'})
		else:
			return render(request, 'volunto/login.html', {'error_message': 'Invalid login'})
	return render(request, 'volunto/login.html')	

#User submits the form filled with data in a POST request
def register(request):
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			user= form.save(commit=False)
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user.set_password(password)
			user.save()
			user = authenticate(username=username, password=password)
			login(request, user)
			return render(request,'volunto/registersuccess.html')
	else:
		form = UserForm()
	return render(request, 'volunto/registration_form.html', {'form': form})


def logout_user(request):
	return render(request, 'volunto/logout.html')		

#Views for Projects 
class ProjectListView(LoginRequiredMixin,generic.ListView):
	model = Project
	context_object_name = 'projects_list'
	queryset = Project.objects.all()
	template_name = 'volunto/project_list.html'

	def get_queryset(self):
		return Project.objects.all()
	def get_context_data(self, **kwargs):
		context = super(ProjectListView, self).get_context_data(**kwargs)
		context['Temp data'] = 'Temp data for projects'
		return context

class ProjectDetailView(LoginRequiredMixin,generic.DetailView):
	model = Project
	template_name = "volunto/project_detail.html"

class ProjectCreate(LoginRequiredMixin,CreateView):
	model = Project
	fields = '__all__'

class ProjectUpdate(LoginRequiredMixin, UpdateView):
	model = Project
	fields = '__all__'
class ProjectDelete(LoginRequiredMixin,DeleteView):
	model = Project
	success_url = reverse_lazy('volunto:projects')


#Views for Organizations
class OrganizationListView(LoginRequiredMixin,generic.ListView):
	model = Organization 
	queryset = Organization.objects.all()
	context_object_name = 'organizations_list'
	template_name = 'volunto/organization_list.html'

	def get_queryset(self):
		return Organization.objects.all()
	def get_context_data(self, **kwargs):
		context = super(OrganizationListView, self).get_context_data(**kwargs)
		context['Temp data'] = 'Temp data for org'
		return context

class OrganizationDetailView(generic.DetailView):
	model = Organization
	template_name = 'volunto/organization_detail.html'

# Views for Application
class ApplicationCreate(LoginRequiredMixin,CreateView):
	model = Application
	fields = '__all__'
	success_url = 'application_sent/'

def application_sent(request):
	return render(request, 'volunto/application_sent.html')


# Views for user Profile
@login_required
def edit_profile(request, pk):
	#Get User object from url
	user = User.objects.get(pk=pk)
	#Populate Profile form with values retrieved from db query using object above
	profile_form = UserForm(instance=user)
	ProfileInlineFormset = inlineformset_factory(User, Profile, fields=('phone', 'bio', 'location', 'experience_level', 'experience_area', 'education_level'))
	formset = ProfileInlineFormset(instance=user)
	if request.user.is_authenticated() and request.user.id == user.id:
		if request.method == POST:
			user_form = UserForm(request.POST, instance=user)
			formset = ProfileInlineFormset(request.POST, instance=user)

			if user_form.is_valid():
				created_user = user_form.save(commit=False)
				formset = ProfileInlineFormset(request.POST, instance=created_user)

				if formset.is_valid():
					created_user.save()
					formset.save()
					return HttpResponseRedirect('/accounts/profile/')
		return render(request, "account/profile_update.html"),{
			"profile_render": pk,
			"profile_render_form": user_form,
			"formset": formset,
		}
	else:
		raise PermissionDenied

@method_decorator(login_required, name='dispatch')
class ProfileDetail(ProfileGetObjectMixin,DetailView):
	model = Profile

@method_decorator(login_required, name='dispatch')
class ProfileUpdate(ProfileGetObjectMixin,UpdateView):
	model = Profile
	fields = '__all__'

#These views are to be used in near future
@login_required
def join_project(request):
	if request.method == 'POST':
		form = ProjectsForm(request.POST)
		if form.is_valid():
			project = form.save(commit=False)
			projectname = form.cleaned_data.get('projectname')
			projdesc = form.cleaned_data.get('password')
			projstatus = form.cleaned_data.get('projstatus')
			project.save()
			return render(request,'volunto/project_success.html')
	else:
		form = ProjectsForm()
	return render(request, 'volunto/project_join.html')

volunto/templates/volunto/application_form.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Volunteer Application{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

volunto/templates/volunto/application_sent.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Application Sent{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="alert alert-success">
    <strong>Your application has been sent!</strong>
    <p>You've successfully created an application for the project and it will be reviewed!
    Click <a href="{% url 'volunto:projects'%}">here</a> to return to Projects list.
	</p>
  </div>
</div>

{% endblock %}

volunto/templates/volunto/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
    	<div class="alert alert-danger">
    		<strong>{{ field.errors }}</strong> T
 		</div>
            <!--<span class="text-danger small">{{ field.errors }}</span>-->
        </div>
        <!--
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>-->
    </div>
{% endfor %}

volunto/templates/volunto/index.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Index{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
            	<h2>Welcome to Volunto's Homepage.</h2>
            	<p>Volunto is still a work in-progress but will be continuously updated.
            		For now, basic features such as user registration, log-in, projects display, and 
            	organization displays are only available.</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

volunto/templates/volunto/logout.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Log Out{% endblock %}

{% block content %}
<p>Logged out!</p>  

<a href="{% url 'volunto:login_user'%}">Click here to login again.</a>
{% endblock %}

volunto/templates/volunto/organization_detail.html
{% extends "volunto/base_visitor.html" %}

{% block content %}

<h1>Organization Name: {{ organization.orgname }}</h1>

<p><strong>Organization Description:</strong> {{ organization.orgdesc }}</p>
<p><strong>Organization Status:</strong> {{ organization.get_org_status }}</p>
{% endblock %}

volunto/templates/volunto/organization_list.html
{% extends 'volunto/base_visitor.html' %}
{% block content %}
<div class="container-fluid">
    <div class="panel panel-default col-sm-4 col-md-4">
      <div class="panel-heading">
        <h1 text-align="center">Organizations List</h1>
      </div>
    <div class="panel-body">
    {% if organizations_list %}
    <ul class="nav nav-pills nav-stacked">
      {% for organization in organizations_list %}
      <div class="well">
      <li>
        <a href="{{ organization.get_absolute_url }}">{{ organization.orgname }}</a> 
      </li>
    </div>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no organizations currently active.</p>
    {% endif %}
  </div>
      </div>
</div>     
{% endblock %}

volunto/templates/volunto/profile_detail.html
{% extends "volunto/base_visitor.html" %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}User Profile{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
<div class="container-fluid">
	<div class="card" style="width:400px" mx-auto>
		<div class="card-header">
		<h2>{{ user.get_username}}'s Profile</h2>
		</div>
		<div class="card-block">
		<p class="card-text">
		First Name: {{ user.get_short_name }} <br>
		Last Name: {{ request.user.last_name}} <br>
		Biography: {{ user.profile.bio }} <br>
		Location: {{ user.profile.location}} <br>
		Phone: {{ user.profile.phone }} <br>
		Experience Level: {{ user.profile.experience_level }} <br>
		Area of Experience: {{ user.profile.experience_area }} <br>
		Education Level: {{ user.profile.education_level }} <br>
		</p>
		</div>
	</div>
</div>
{% endblock %}
</body>
</html>

volunto/templates/volunto/profile_form.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Update User Profile{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Update User Profile</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{{ profile.get_update_url}}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }} 
                                <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#myModal">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

volunto/templates/volunto/project_confirm_delete.html
{% extends 'volunto/base_visitor.html' %}
{% block content %}
<div class="container-fluid">
    <div class="panel panel-default col-sm-4 col-md-4">
      <div class="panel-heading">
        <h1 text-align="center">Project Deletion</h1>
      </div>
    <div class="panel-body">
      <p>Are you sure you want to delete the project: {{ project }}?</p>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete." />
        <a href
      </form>
    </div>
    </div>
</div>     
{% endblock %}

volunto/templates/volunto/project_form.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Add a new Project{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

volunto/templates/volunto/project_success.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Project Creation Success{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="alert alert-success">
    <strong>Project Creation Successful!</strong>
    <p>You've successfully created a project and it's activate!
    Click <a href="{% url 'volunto:projects'%}">here</a> to return to Projects list.
	</p>
  </div>
</div>

{% endblock %}

volunto/templates/volunto/registersuccess.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Registration Success{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="alert alert-success">
    <strong>Registration Successful!</strong>
    <p>You've successfully registered and your account is now active!
    Click <a href="{% url 'volunto:index'%}">here</a> to return to Volunto's index.
	</p>
  </div>
</div>

{% endblock %}

volunto/templates/volunto/registration_form.html
{% extends 'volunto/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for a Volunto account</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}                     
                                {% if field.help_text %}
                                  <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button type="submit" class="btn btn-success" data-toggle="modal" data-target="#myModal">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}